---
- name: Script Home Directory State
  stat:
    path: "{{ synology_tun__scripts_home }}"
  register: script_directory_state

- name: Install synology-tun service
  when: synology_tun__state != "absent"
  include_tasks: install.yml

- name: Uninstall synology-tun service
  when: synology_tun__state == "absent" and script_directory_state.stat.exists
  include_tasks: uninstall.yml
