---
- name: reload systemd daemons
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Get Service Status
  become: true
  ansible.builtin.systemd:
    name: "synology-tun.service"
  register: current_service_state

- name: stop service
  become: true
  ansible.builtin.systemd:
    name: "synology-tun.service"
    state: stopped
    enabled: no
  when: current_service_state.status and current_service_state.status.ActiveState != "stopped"
  register: service_state
  failed_when: service_state.status.ActiveState == "failed"

- name: Remove files
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ synology_tun__scripts_home }}/synology-tun.sh"
    - "{{ synology_tun__systemd_home }}/synology-tun.service"

- name: reload systemd daemons
  become: True
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Remove target path
  become: true
  file:
    dest: "{{ synology_tun__scripts_home }}/"
    state: absent
  changed_when: false
